#!/usr/bin/env bash
set -euo pipefail

main_dir="$(cd "$(dirname "$0")" && pwd)"
bundle_path="$main_dir/AlphaUI_Bundle.lua"

source_files=(
  "AlphaUI_UI.lua"
  "BuffDurations.lua"
  "InstantQuestText.lua"
  "UnitFrames.lua"
  "ActionBars.lua"
  "Clock.lua"
  "AlwaysTrack.lua"
  "MergedBags.lua"
  "TalentButton.lua"
  "TargetAuras.lua"
  "TargetDistance.lua"
  "TutorialExtend.lua"
  "ExtendedStats.lua"
  "ReloadButton.lua"
  "ChatCopy.lua"
  "ClientTweaks.lua"
  "ClassPortraits.lua"
  "GuildFrame.lua"
  "AtlasLoot_Data.lua"
  "AtlasLoot.lua"
  "AlphaUI_Slash.lua"
)

{
  printf '%s\n' "-- This file is generated by build_bundle.sh."
  printf '%s\n' "-- 0.5.3 only reliably loads the first six <Script file=\"...\"/> entries in AlphaUI.xml,"
  printf '%s\n' "-- so module/source files are bundled here while staying split on disk for maintenance."
  printf '\n'

  for source_file in "${source_files[@]}"; do
    printf '%s\n' "-- BEGIN ${source_file}"
    printf '%s\n' "do"
    cat "$main_dir/$source_file"
    printf '\n%s\n' "end"
    printf '%s\n' "-- END ${source_file}"
    printf '\n'
  done
} > "$bundle_path"
